pragma solidity ^0.8.17;

library Images {
    string public constant UNREVEALED = "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAAAnJycAAABUVFTztD9wAAAAAXRSTlMAQObYZgAAABVJREFUGNNjGDyABcbQhTE4GAYcAAAgKAA6oPTpgwAAAABJRU5ErkJggg==";
    string public constant GATHERER =
        "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAAD///+D3c/SAAAAAXRSTlMAQObYZgAAAB1JREFUGNNjoCkIdYDQjKsmQBhsy5bARRBqBjEAAGQRBPHyQj4NAAAAAElFTkSuQmCC";
    string public constant PROTECTOR =
        "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAKlBMVEUAAAD////p4iWRy2kkUpmtKZUlrjsAxfAwY9O6Rp3esC/aPDaGIiexHRjD61CUAAAAAXRSTlMAQObYZgAAADFJREFUKM9jGNqA5/YiIbPkCpFIuMguRWUG80ZXhBKgAgZkBQyMygkMjK4TGEYBEQAAmnoIPpGtZsYAAAAASUVORK5CYII=";
    string public constant WOLF =
        "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAQMAAABJtOi3AAAABlBMVEUAAAAAAAClZ7nPAAAAAXRSTlMAQObYZgAAABRJREFUCNdjIBcIOAAJjgYkLk0AAG9gASkMl47GAAAAAElFTkSuQmCC";
}
